[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.8.14,<0.9.0" ]

[project]
name = "amgi-sqs-event-source-mapping"
version = "0.25.1"
description = "AMGI SQS event source mapping handler"
readme = "README.md"
authors = [
  { name = "jack.burridge", email = "jack.burridge@mail.com" },
]
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "amgi-common==0.25.1",
  "amgi-types==0.25.1",
]

[dependency-groups]
dev = [
  "boto3>=1.40.70",
  "test-utils",
  "testcontainers[localstack]>=4.13.0",
]

[tool.uv.sources]
test-utils = { workspace = true }
amgi-common = { workspace = true }
amgi-types = { workspace = true }
