[project]
name = "amgi-aiopika-amqp"
version = "0.21.0"
description = "AMQP AMGI server implementation using aio-pika"
readme = "README.md"
authors = [{ name = "Jack Burridge", email = "jack.burridge@mail.com" }]
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "amgi-common==0.21.0",
    "amgi-types==0.21.0",
    "aio-pika>=9.0.0",
]

[project.entry-points.amgi_server]
amgi-aiopika-amqp = "amgi_aiopika_amqp:_run_cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/amgi_aiopika_amqp"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.24.0",
    "testcontainers>=4.9.0",
    "pika>=1.3.0",
]

[tool.uv.sources]
amgi-common = { workspace = true }
amgi-types = { workspace = true }

[tool.pytest.ini_options]
testpaths = ["tests_amgi_aiopika_amqp"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"